# Generated by Django 5.1.2 on 2025-01-13 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facebook", "0002_facebookcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToxicityParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toxic", models.BooleanField(default=False)),
                ("severe_toxic", models.BooleanField(default=False)),
                ("obscene", models.BooleanField(default=False)),
                ("threat", models.BooleanField(default=False)),
                ("insult", models.BooleanField(default=False)),
                ("identity_hate", models.BooleanField(default=False)),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="toxicity_parameters",
                        to="facebook.facebookcomment",
                    ),
                ),
            ],
        ),
    ]
