# Generated by Django 5.1.2 on 2025-01-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeletedComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("user_name", models.CharField(blank=True, max_length=255, null=True)),
                ("toxic", models.BooleanField(default=False)),
                ("severe_toxic", models.BooleanField(default=False)),
                ("obscene", models.BooleanField(default=False)),
                ("threat", models.BooleanField(default=False)),
                ("insult", models.BooleanField(default=False)),
                ("identity_hate", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                ("reason_for_deletion", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
