# Generated by Django 5.1.2 on 2025-01-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_commentstats"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentstats",
            name="is_model_serving",
            field=models.BooleanField(default=False),
        ),
    ]
