# Generated by Django 5.1.2 on 2025-02-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_commentstats_is_model_serving"),
        ("facebook", "0005_remove_facebookpost_last_fetched_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deletedcomment",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleted_comments",
                to="facebook.facebookpost",
            ),
        ),
    ]
