# Generated by Django 5.1.2 on 2025-01-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacebookComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment_id", models.CharField(max_length=255, unique=True)),
                ("user_name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="facebook.facebookpost",
                    ),
                ),
            ],
        ),
    ]
