# Generated by Django 5.1.2 on 2025-01-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook", "0002_facebookcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookcomment",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
