# Generated by Django 5.1.2 on 2025-02-04 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facebook", "0004_facebookpost_last_fetched_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facebookpost",
            name="last_fetched_time",
        ),
        migrations.AddField(
            model_name="facebookpost",
            name="fetched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fetched_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
